spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/sharing?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.sharing.pojo
pagehelper:
  helperDialect: mysql #数据方言
  reasonable: true #
  supportMethodsArguments: true
  params: count=countSql